### ISSUE TITLE
bot crashing on heroku

### ISSUE THREAD

**Issue by shanuflash** [SudhanPlayz/Discord-MusicBot#1017]
```    
at Object.module.exports [as MESSAGE_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
TypeError: Cannot read properties of undefined (reading 'cache')
     at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
                                         ^
     at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:517:14)
     at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
       const existing = channel.messages.cache.get(data.id);
     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:132:16)
     at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
     at Receiver.emit (node:events:527:28)
 /app/node_modules/discord.js/src/client/actions/MessageCreate.js:11
     at WebSocket.emit (node:events:527:28)
     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1068:20)
     at MessageCreateAction.handle (/app/node_modules/discord.js/src/client/actions/MessageCreate.js:11:41)
Process exited with status 1
```
- bot version: v4
- discord.js version: v12.5.3
- Node.js version: v16.16.0
- Operating system: (Heroku)

Constant crashes while running on heroku, any help?

**Comment by JotaroKujo0525** [comment]
v4 deprecated version,it's inevitable, recommend you to restart your app or switch to other hosts. again, if this exists, it's inevitable because v4 is using a deprecated version of djs which means deprecated discord api.


please ask in the discord server if you need more assistance

**Comment by voaii** [comment]
I'm using the latest everything and still have this error. i'm new to this bot so everything is fresh
