### ISSUE TITLE
erroes

### ISSUE THREAD

**Issue by Toodo** [SudhanPlayz/Discord-MusicBot#1061]
**Please describe the problem you are having in as much detail as possible: After som hrs the bot crashed/restart then i get a error massage**

### Essentials:

- Bot Version: v5 #1060
- Commit Hash:
- Node.js version: replit 16
- Operating system: replit

#### Additional system info
- Is it virtualized? (Docker or ...) :
- What CPU is it running on (X86 or ARM or...):
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

TypeError: Cannot read properties of null (reading 'username')
    at /home/runner/musicv5/api/routes/data.js:9:21
    at Layer.handle [as handle_request] (/home/runner/musicv5/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/musicv5/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/runner/musicv5/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/runner/musicv5/node_modules/express/lib/router/layer.js:95:5)
    at /home/runner/musicv5/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/runner/musicv5/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/musicv5/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/runner/musicv5/node_modules/express/lib/router/index.js:175:3)
    at router (/home/runner/musicv5/node_modules/express/lib/router/index.js:47:12)

**Comment by JotaroKujo0525** [comment]
it's website related :)

**Comment by Toodo** [comment]
okey but the bot does not work when that happends

**Comment by JotaroKujo0525** [comment]
you're being rate limited :)

**Comment by Toodo** [comment]
so i just have to wait if i get that massage again?

**Comment by JotaroKujo0525** [comment]
the message is normal because is v5,the dashboard is still not complete

the reason why your bot isn't logging in because you were being rate limited. Please stop running your code for awhile. Or alternatively, type `kill 0` or `kill 1`on your shell

**Comment by Toodo** [comment]
okey then i know thanks
