### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by blaze534** [SudhanPlayz/Discord-MusicBot#1088]
i have this bug 

node_modules\discord.js\src\client\actions\Action.js:27
    const existing = manager.cache.get(id);
                             ^

TypeError: Cannot read properties of undefined (reading 'cache')
    at MessageUpdateAction.getPayload (C:\Users\Utente\Desktop\BOTS\DOGMC_MUSIC\node_modules\discord.js\src\client\actions\Action.js:27:30)
    at MessageUpdateAction.getMessage (C:\Users\Utente\Desktop\BOTS\DOGMC_MUSIC\node_modules\discord.js\src\client\actions\Action.js:55:12)
    at MessageUpdateAction.handle (C:\Users\Utente\Desktop\BOTS\DOGMC_MUSIC\node_modules\discord.js\src\client\actions\MessageUpdate.js:10:28)
    at Object.module.exports [as MESSAGE_UPDATE] (C:\Users\Utente\Desktop\BOTS\DOGMC_MUSIC\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_UPDATE.js:6:57)
    at WebSocketManager.handlePacket (C:\Users\Utente\Desktop\BOTS\DOGMC_MUSIC\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\Utente\Desktop\BOTS\DOGMC_MUSIC\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\Utente\Desktop\BOTS\DOGMC_MUSIC\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\Utente\Desktop\BOTS\DOGMC_MUSIC\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (C:\Users\Utente\Desktop\BOTS\DOGMC_MUSIC\node_modules\ws\lib\websocket.js:1068:20)
i have node v16.15.1. and im on windows 11

**Comment by DarrenOfficial** [comment]
Insufficient information.
