### ISSUE TITLE
Replit issue

### ISSUE THREAD

**Issue by C-EO** [SudhanPlayz/Discord-MusicBot#1101]
**Please describe the problem you are having in as much detail as possible:**

The bot starts on first run, and stops finishing booting on all other runs

### Essentials:

- Bot Version: v5.0.0-beta
- Commit Hash: 581eb90
- Node.js version: v18
- Operating system:  linux 5.13.0-1025-gcp

#### Additional system info
- Is it virtualized? (Docker or ...) : Replit
- What CPU is it running on (X86 or ARM or...): ARM
- Additional details that might help us figure out the problem: I don't think.

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by C-EO** [comment]
node index.js
Replit system detected, initiating special `unhandledRejection` event listener.
Make sure to fill in the config.js before starting the bot.
[11:9:2022 - 20:24] | Started the bot...
[11:9:2022 - 20:24] | Slash Command Loaded: 247
[11:9:2022 - 20:24] | Slash Command Loaded: autopause
[11:9:2022 - 20:24] | Slash Command Loaded: autoqueue
[11:9:2022 - 20:24] | Slash Command Loaded: clean
[11:9:2022 - 20:24] | Slash Command Loaded: clear
[11:9:2022 - 20:24] | Slash Command Loaded: disconnect
[11:9:2022 - 20:24] | Slash Command Loaded: filters
[11:9:2022 - 20:24] | Slash Command Loaded: help
[11:9:2022 - 20:24] | Slash Command Loaded: invite
[11:9:2022 - 20:24] | Slash Command Loaded: loop
[11:9:2022 - 20:24] | Slash Command Loaded: loopq
[11:9:2022 - 20:24] | Slash Command Loaded: lyrics
[11:9:2022 - 20:24] | Slash Command Loaded: move
[11:9:2022 - 20:24] | Slash Command Loaded: nowplaying
[11:9:2022 - 20:24] | Slash Command Loaded: pause
[11:9:2022 - 20:24] | Slash Command Loaded: ping
[11:9:2022 - 20:24] | Slash Command Loaded: play
[11:9:2022 - 20:24] | Slash Command Loaded: poker
[11:9:2022 - 20:24] | Slash Command Loaded: previous
[11:9:2022 - 20:24] | Slash Command Loaded: queue
[11:9:2022 - 20:24] | Slash Command Loaded: reload
[11:9:2022 - 20:24] | Slash Command Loaded: remove
[11:9:2022 - 20:24] | Slash Command Loaded: replay
[11:9:2022 - 20:24] | Slash Command Loaded: resume
[11:9:2022 - 20:24] | Slash Command Loaded: save
[11:9:2022 - 20:24] | Slash Command Loaded: search
[11:9:2022 - 20:24] | Slash Command Loaded: seek
[11:9:2022 - 20:24] | Slash Command Loaded: shuffle
[11:9:2022 - 20:24] | Slash Command Loaded: skip
[11:9:2022 - 20:24] | Slash Command Loaded: skipto
[11:9:2022 - 20:24] | Slash Command Loaded: stats
[11:9:2022 - 20:24] | Slash Command Loaded: stop
[11:9:2022 - 20:24] | Slash Command Loaded: summon
[11:9:2022 - 20:24] | Slash Command Loaded: volume
[11:9:2022 - 20:24] | Slash Command Loaded: youtube
[11:9:2022 - 20:24] | ContextMenu Loaded: hi
[11:9:2022 - 20:24] | Event Loaded: interactionCreate
[11:9:2022 - 20:24] | Event Loaded: messageCreate
[11:9:2022 - 20:24] | Event Loaded: messageDelete
[11:9:2022 - 20:24] | Event Loaded: raw
[11:9:2022 - 20:24] | Event Loaded: ready
[11:9:2022 - 20:24] | Event Loaded: voiceStateUpdate
TypeError: Cannot read properties of null (reading 'username')
    at /home/runner/imperialbotmusic/api/routes/data.js:9:21
    at Layer.handle [as handle_request] (/home/runner/imperialbotmusic/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/imperialbotmusic/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/runner/imperialbotmusic/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/runner/imperialbotmusic/node_modules/express/lib/router/layer.js:95:5)
    at /home/runner/imperialbotmusic/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/runner/imperialbotmusic/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/imperialbotmusic/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/runner/imperialbotmusic/node_modules/express/lib/router/index.js:175:3)
    at router (/home/runner/imperialbotmusic/node_modules/express/lib/router/index.js:47:12)
TypeError: Cannot read properties of null (reading 'username')
    at /home/runner/imperialbotmusic/api/routes/data.js:9:21
    at Layer.handle [as handle_request] (/home/runner/imperialbotmusic/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/imperialbotmusic/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/runner/imperialbotmusic/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/runner/imperialbotmusic/node_modules/express/lib/router/layer.js:95:5)
    at /home/runner/imperialbotmusic/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/runner/imperialbotmusic/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/imperialbotmusic/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/runner/imperialbotmusic/node_modules/express/lib/router/index.js:175:3)
    at router (/home/runner/imperialbotmusic/node_modules/express/lib/router/index.js:47:12)

**Comment by C-EO** [comment]
the above is the error

**Comment by JaRappa** [comment]
I am having the same issue with the same error

**Comment by JaRappa** [comment]
TypeError: Cannot read properties of null (reading 'username')
    at /home/runner/Discord-MusicBot/api/routes/data.js:9:21
    at Layer.handle [as handle_request] (/home/runner/Discord-MusicBot/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/Discord-MusicBot/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/runner/Discord-MusicBot/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/runner/Discord-MusicBot/node_modules/express/lib/router/layer.js:95:5)
    at /home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:175:3)
    at router (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:47:12)

**Comment by DarrenOfficial** [comment]
Try now. I just pushed an update

**Comment by JaRappa** [comment]
i pulled so that i am up to date with v5 and now it gives the following after trying to run

node index.js
nix error: building nix env: exit status 1
Output has been trimmed to the last 20 lines
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/top-level/stage.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/stdenv/adapters.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/build-support/trivial-builders.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/top-level/splice.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/top-level/all-packages.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/top-level/aliases.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/stdenv/generic/default.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/lib/customisation.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/tools/text/gawk/default.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/servers/x11/xorg/default.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/servers/x11/xorg/overrides.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/stdenv/generic/make-derivation.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/build-support/mkshell/default.nix'
evaluating file '/home/runner/Discord-MusicBot/replit.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/stdenv/generic/check-meta.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/lib/systems/doubles.nix'
copied source '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/stdenv/generic/default-builder.sh' -> '/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh'
error: attribute 'nodejs-17_x' missing, at /home/runner/Discord-MusicBot/replit.nix:3:3
(use '--show-trace' to show detailed location information)

sh: 1: node: not found
exit status 127
nix error: building nix env: exit status 1
Output has been trimmed to the last 20 lines
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/top-level/stage.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/stdenv/adapters.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/build-support/trivial-builders.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/top-level/splice.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/top-level/all-packages.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/top-level/aliases.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/stdenv/generic/default.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/lib/customisation.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/tools/text/gawk/default.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/servers/x11/xorg/default.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/servers/x11/xorg/overrides.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/stdenv/generic/make-derivation.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/build-support/mkshell/default.nix'
evaluating file '/home/runner/Discord-MusicBot/replit.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/stdenv/generic/check-meta.nix'
evaluating file '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/lib/systems/doubles.nix'
copied source '/nix/store/d755j96xhbwa2q32mgwbbxzbx7x69p5h-nixpkgs-22.05-src/pkgs/stdenv/generic/default-builder.sh' -> '/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh'
error: attribute 'nodejs-17_x' missing, at /home/runner/Discord-MusicBot/replit.nix:3:3
(use '--show-trace' to show detailed location information)

**Comment by GazorHuman** [comment]
Nix doesn't have NodeJS v17, They skipped NodeJS versions from 16 to 18. 
You can fix this error by changing the NodeJS version on replit.nix file Here is the code.

`{ pkgs }: {
	deps = [
    pkgs.nodejs-18_x
	];
}`

If you can't find the replit.nix file (it's hidden by default) you need to show hidden files on replit, I have a guide for you to find the replit.nix file [Click this link](https://imgur.com/a/JepqLpC)

**Comment by DarrenOfficial** [comment]
My bad, I forgot 17 does not exist :p

**Comment by DarrenOfficial** [comment]
I thought I saw 17 [here](https://search.nixos.org/packages?channel=22.05&show=nodejs-16_x&from=0&size=50&sort=relevance&type=packages&query=nodejs). Anyhow I changed it to 18 and it should work again.

**Comment by MiracleCherryPie** [comment]
so pull request when?

**Comment by MiracleCherryPie** [comment]
@GazorHuman

**Comment by GazorHuman** [comment]
> so pull request when?

Darren already changed it

**Comment by JaRappa** [comment]
i updated the replit.nix file but i got the original error 

TypeError: Cannot read properties of null (reading 'username')
    at /home/runner/Discord-MusicBot/api/routes/data.js:9:21
    at Layer.handle [as handle_request] (/home/runner/Discord-MusicBot/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/Discord-MusicBot/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/runner/Discord-MusicBot/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/runner/Discord-MusicBot/node_modules/express/lib/router/layer.js:95:5)
    at /home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:175:3)
    at router (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:47:12)

i tried running with both NodeJS 18 and NodeJS 16

**Comment by DarrenOfficial** [comment]
[config.js#L5](https://github.com/SudhanPlayz/Discord-MusicBot/blob/v5/config.js#L5) is this filled?

**Comment by JaRappa** [comment]
yes and it is correct. I created a new installation on replit and copied over the config.js and it worked. the original still does not though.

**Comment by C-EO** [comment]
mine just keeps picking random times to work

**Comment by GazorHuman** [comment]
> mine just keeps picking random times to work

Would you mind checking my email?

**Comment by C-EO** [comment]
i still have the problem

**Comment by GazorHuman** [comment]
> i still have the problem

Try running `kill 1` in the replit shell and start it again

**Comment by C-EO** [comment]
`kill 1` works temporarily
it's not long-term fix

**Comment by MiracleCherryPie** [comment]
> `kill 1` works temporarily it's not long-term fix

ofc it's temporary fix as replit is got ratelimited by discord. I suggest @SudhanPlayz to add Discord-Linux bot to the support server

**Comment by MiracleCherryPie** [comment]
@C-EO out of curiousity when gcp has arm compute engine instance and replit gonna use it
