### ISSUE TITLE
Error searching and playing Spotify

### ISSUE THREAD

**Issue by julian-piehl** [SudhanPlayz/Discord-MusicBot#1112]
When I'm trying to play a song by name, I get 
```
Got request to load for identifier "ytsearch:Songname"
No matches found
```

When I'm trying to play a song using a Spotify link, I get
```
Got request to load for identifier "ytsearch:Songname"
No matches found

/usr/src/app/node_modules/erela.js/dist/structures/Utils.js:75
throw new RangeError('Argument "data" must be present.');
           ^
RangeError: Argument "data" must be present.
     at Function.build (/usr/src/app/node_modules/erela.js/dist/structures/Utils.js:75:19)
     at Object.run (/usr/src/app/commands/play.js:278:41)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)

Connection closed from /172.18.0.3:45116 CloseStatus[code=1006, reason=]
Shutting down 0 playing players.
```
And the Slash Command times out.

When I'm using a YouTube link, everything is fine.
```
Got request to load for identifier "https://www.youtube.com/watch?v=code"
Loaded track Songname
```

**Comment by kiyoshikuncool** [comment]
Which bot version are you use and which version the lavalink is, my friend?
