### ISSUE TITLE
Bot not playing music and non-slash commands have no response

### ISSUE THREAD

**Issue by iggyvilla** [SudhanPlayz/Discord-MusicBot#1117]
### Essentials:

- Bot Version: cloned main
- Commit Hash: 
- Node.js version: v16.18.1 (tried v18 also)
- Operating system:

#### Additional system info
- Ubuntu
- X86
- Hosting bot on **my own system** (not on replit). Lavalink is installed and works.

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

Slash commands only work and the default `>` commands don't. When using /play, bot joins the channel but doesn't play any music. This error immediately pops up:
```
/home/bigpp/music_bots/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Interaction has already been acknowledged.
    at RequestHandler.execute (/home/bigpp/music_bots/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/bigpp/music_bots/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async Object.interaction.send (/home/bigpp/music_bots/Discord-MusicBot/structures/DiscordMusicBot.js:92:16) {
  method: 'post',
  path: '/interactions/1039432919518814289/aW50ZXJhY3Rpb246MTAzOTQzMjkxOTUxODgxNDI4OTpMRjYxYWQ2WEhTWDRaZXdUWU1xWWVjWEcwV0hrT0ZXZUFTd3FwZXFPNGY0QlkxQ1BuSU85ZXN2UzZiTE9teHl1YWRMNFI5WEFUS3lsV21jbDVLeVdzSG01a2prZG5hamxMMXR0WDdNVlZSb3JTdWFEYVI0NEdHNDhXYmlldldEOA/callback',
  code: 40060,
  httpStatus: 400
}
```

Logs:
```
8:10:2022 - 7:7 | Info: Event Loaded: guildCreate
8:10:2022 - 7:7 | Info: Event Loaded: message
8:10:2022 - 7:7 | Info: Event Loaded: raw
8:10:2022 - 7:7 | Info: Event Loaded: ready
8:10:2022 - 7:7 | Info: Event Loaded: voiceStateUpdate
8:10:2022 - 7:7 | Info: Command Loaded: bassboost
8:10:2022 - 7:7 | Info: Command Loaded: bump
8:10:2022 - 7:7 | Info: Command Loaded: clear
8:10:2022 - 7:7 | Info: Command Loaded: config
8:10:2022 - 7:7 | Info: Command Loaded: disconnect
8:10:2022 - 7:7 | Info: Command Loaded: grab
8:10:2022 - 7:7 | Info: Command Loaded: help
8:10:2022 - 7:7 | Info: Command Loaded: invite
8:10:2022 - 7:7 | Info: Command Loaded: loop
8:10:2022 - 7:7 | Info: Command Loaded: loopqueue
8:10:2022 - 7:7 | Info: Command Loaded: lyrics
8:10:2022 - 7:7 | Info: Command Loaded: move
8:10:2022 - 7:7 | Info: Command Loaded: nowplaying
8:10:2022 - 7:7 | Info: Command Loaded: pause
8:10:2022 - 7:7 | Info: Command Loaded: play
8:10:2022 - 7:7 | Info: Command Loaded: queue
8:10:2022 - 7:7 | Info: Command Loaded: remove
8:10:2022 - 7:7 | Info: Command Loaded: resume
8:10:2022 - 7:7 | Info: Command Loaded: search
8:10:2022 - 7:7 | Info: Command Loaded: seek
8:10:2022 - 7:7 | Info: Command Loaded: shuffle
8:10:2022 - 7:7 | Info: Command Loaded: skip
8:10:2022 - 7:7 | Info: Command Loaded: skipto
8:10:2022 - 7:7 | Info: Command Loaded: stats
8:10:2022 - 7:7 | Info: Command Loaded: volume
8:10:2022 - 7:7 | Info: Command Loaded: youtube
8:10:2022 - 7:7 | Info: Successfully Logged in as ---
8:10:2022 - 7:7 | Info: Registering slash commands for 466113837918060555
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: bassboost
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: bump
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: clear
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: config
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: disconnect
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: grab
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: help
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: invite
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: loop
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: loopqueue
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: lyrics
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: move
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: nowplaying
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: pause
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: play
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: queue
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: remove
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: resume
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: search
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: shuffle
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: skip
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: skipto
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: stats
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: volume
8:10:2022 - 7:7 | Info: [Slash Command]: [POST] Guild 466113837918060555, Command: youtube
8:10:2022 - 7:7 | Info: Lavalink: Node Main connected
```

botconfig.js:
```
module.exports = {
  Admins: ["xxx"], // Admins of the bot, I don't know what this do. -Darren.
  ExpressServer: false, // If you wanted to make the website run or not
  DefaultPrefix: process.env.Prefix || ">", // Default prefix, Server Admins can change the prefix
  Port: 3250, //Which port website gonna be hosted
  SupportServer: "https://discord.gg/sbySMS7m3v", // Support Server Link
  Token: process.env.Token || "xxx", // Discord Bot Token
  ClientID: process.env.Discord_ClientID || "xxx", // Discord Client ID
  ClientSecret: process.env.Discord_ClientSecret || "xxx", // Discord Client Secret
  Scopes: ["identify", "guilds", "applications.commands"], // Discord OAuth2 Scopes
  ServerDeafen: true, // If you want bot to stay deafened
  DefaultVolume: 50, // Sets the default volume of the bot, You can change this number anywhere from 1 to 9007199254740991 (JS Integer limit. If you do set it to that, you're a monster.)
  CallbackURL: "/api/callback", // Discord API Callback url. Do not touch it if you don't know what you are doing. All you need to change for website to work is on line 20.
  "24/7": true, // Make the bot stays in VC 24/7 (when you reboot the bot will **not** automatically rejoin.)
  CookieSecret: "Pikachu is cute", // A cookie for you, cookie for me. make sure you change this value!
  IconURL:
    "https://raw.githubusercontent.com/SudhanPlayz/Discord-MusicBot/master/assets/logo.gif", // URL of all embed author icons | Dont edit unless you dont need that Music CD Spining
  EmbedColor: "#0c0d0d", // Color of most embeds | Custom Hex value are supported. I.e: "#36393F"
  Permissions: 2205281600, // Bot Inviting Permissions
  Website: process.env.Website || "http://localhost", // Website where it is hosted at includes http or https || Use "0.0.0.0" if you using Heroku || Do not include /api/callback. Just the website url. I.e. "https://foo.bar"
  // If you get invalid oauth, make sure on the discord developer page you set the oauth url to something like: https://example.com/api/callback.

  Presence: {
    status: "online", // You can show online, idle, and dnd
    name: "Music", // The message shown
    type: "LISTENING", // PLAYING, WATCHING, LISTENING, STREAMING
  },

  // You need a lavalink server for this bot to work!!!!
  // Lavalink server; public lavalink -> https://lavalink-list.darrennathanael.com/; create one yourself -> https://darrennathanael.com/post/how-to-lavalink
  Lavalink: {
    id: "Main", //- Used for indentifier. You can set this to whatever you want.
    host: "localhost", //- The host name or IP of the lavalink server.
    port: 2333, // The port that lavalink is listening to. This must be a number!
    pass: "hello", //- The password of the lavalink server.
    secure: false, // Set this to true if the lavalink uses SSL. if not set it to false.
    retryAmount: 200, //- The amount of times to retry connecting to the node if connection got dropped.
    retryDelay: 40, //- Delay between reconnect attempts if connection is lost.
  },
  // Spotify Integration, allows you to enter a spotify link.
  Spotify: {
    ClientID: process.env.Spotify_ClientID || "", // Spotify Client ID
    ClientSecret: process.env.Spotify_ClientSecret || "", // Spotify Client Secret
  },
};
```
Screenshots:
![image](https://user-images.githubusercontent.com/61501690/200499105-c552fc71-2030-45ee-a67d-b6280e2dfb26.jpeg)

**Comment by XstreamSpeed** [comment]
discord.js v12 is no longer supported. use the v5 branch btw

**Comment by LewdHuTao** [comment]
go to discord dev portal and enable message intents to make prefix works in v4. Also i dont recommend you to use v4 as djs 12 not supported anymore
