### ISSUE TITLE
 Info: [Slash Command]: [POST-FAILED] Guild 901102817878622249, Command: disconnect DiscordAPIError: Missing Access

### ISSUE THREAD

**Issue by CarlosA190** [SudhanPlayz/Discord-MusicBot#1133]
2:11:2022 - 14:30 | Info: [Slash Command]: [POST-FAILED] Guild 901102817878622249, Command: disconnect
DiscordAPIError: Missing Access
    at RequestHandler.execute (C:\Users\Microsoft\Downloads\PhoenixStudios\DashBoard Phoenix\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async RequestHandler.push (C:\Users\Microsoft\Downloads\PhoenixStudios\DashBoard Phoenix\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async C:\Users\Microsoft\Downloads\PhoenixStudios\DashBoard Phoenix\util\RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/754152091680768041/guilds/901102817878622249/commands',
  code: 50001,
  httpStatus: 403
}

**Comment by LewdHuTao** [comment]
fill your config.js properly and invite your bot with `application.commands` scope
