### ISSUE TITLE
Replit Bug TypeError: Cannot read properties of null (reading 'username'))

### ISSUE THREAD

**Issue by mikeciyscratch** [SudhanPlayz/Discord-MusicBot#1139]
**Please describe the problem you are having in as much detail as possible:**
### Essentials
- Bot Version: ?
- Commit Hash: v5
- Node.js version: v18.2.0
- Operating system: Linux

#### Additional system info
- Is it virtualized? (Docker or ...) : Replit
- What CPU is it running on (X86 or ARM or...): ARM I think.
- Additional details that might help us figure out the problem:

I get this error:
`TypeError: Cannot read properties of null (reading 'username')
    at /home/runner/Discord-MusicBot/api/routes/data.js:9:21
    at Layer.handle [as handle_request] (/home/runner/Discord-MusicBot/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/Discord-MusicBot/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/runner/Discord-MusicBot/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/runner/Discord-MusicBot/node_modules/express/lib/router/layer.js:95:5)
    at /home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:175:3)
    at router (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:47:12)`

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by johnyfernandes** [comment]
Having the same issue as you, using Repl.it as well. Did you find any solution for this problem?

**Comment by MiracleCherryPie** [comment]
1. `kill 1` in shell
2. Replit is using x86 CPU
3. Don't use replit
