### ISSUE TITLE
Running /queue with 11 or more songs in queue errors out or hangs

### ISSUE THREAD

**Issue by Moolah328** [SudhanPlayz/Discord-MusicBot#1150]
**Please describe the problem you are having in as much detail as possible:**
When there are 11 or more songs in the queue and /queue is run, either the code hangs or the following error is produced. I've done my best to troubleshoot any issues with my setup. Running locally on my PC, hosting my own LavaLink Server.

```
C:\Servers\MusicBot\util\pagination.js:12
  const curPage = await msg.channel.send(
                                    ^

TypeError: Cannot read properties of undefined (reading 'send')
    at module.exports [as Pagination] (C:\Servers\MusicBot\util\pagination.js:12:37)
    at Object.run (C:\Servers\MusicBot\commands\queue.js:221:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.12.1
```
#### Reproduction steps
1. /play 11 songs via playlist or individually
2. Run /queue
3.  Application does not respond and the above error is produced

If there is any other information needed or I have misreported anything please let me know. Thanks!

### Essentials:

- Bot Version: 4.1.4
- Commit Hash: 3e01ad3
- Node.js version: 18.12.1
- Operating system: Windows 10 Pro, 21H2
- discord.js version: 12.5.3

#### Additional system info
- Is it virtualized? (Docker or ...) : No
- What CPU is it running on (X86 or ARM or...): x86

**Comment by Moolah328** [comment]
> Switch to v5

Done and done. Thank you and closing this
