### ISSUE TITLE
Discord Crashes

### ISSUE THREAD

**Issue by itssalsawij** [SudhanPlayz/Discord-MusicBot#1197]
Console crashes and shows this error after playing for quite some time.
latest version, v5
```
Error: Login sessions require session support. Did you forget to use `express-session` middleware?
    at SessionStrategy.authenticate (/home/runner/Discord-MusicBot/node_modules/passport/lib/strategies/session.js:46:41)
    at attempt (/home/runner/Discord-MusicBot/node_modules/passport/lib/middleware/authenticate.js:369:16)
    at authenticate (/home/runner/Discord-MusicBot/node_modules/passport/lib/middleware/authenticate.js:370:7)
    at Layer.handle [as handle_request] (/home/runner/Discord-MusicBot/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:328:13)
    at /home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:280:10)
    at initialize (/home/runner/Discord-MusicBot/node_modules/passport/lib/middleware/initialize.js:98:5)
    at Layer.handle [as handle_request] (/home/runner/Discord-MusicBot/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by Assassin654** [comment]
Ensure you are using the same library versions from the package.json. Specifically the passport library
