### ISSUE TITLE
query not found

### ISSUE THREAD

**Issue by iakzs** [SudhanPlayz/Discord-MusicBot#1279]
I didn't touch the code and i got:
```
 TypeError [COMMAND_INTERACTION_OPTION_NOT_FOUND]: Required option "query" not found.
     at CommandInteractionOptionResolver.get (/home/h/f/Discord-MusicBot/node_modules/discord.js/src/structures/CommandInteractionOptionResolver.js:77:15)
     at CommandInteractionOptionResolver._getTypedOption (/home/h/f/Discord-MusicBot/node_modules/discord.js/src/structures/CommandInteractionOptionResolver.js:94:25)
     at CommandInteractionOptionResolver.getString (/home/h/f/Discord-MusicBot/node_modules/discord.js/src/structures/CommandInteractionOptionResolver.js:159:25)
     at SlashCommand.run (/home/h/f/Discord-MusicBot/commands/slash/play.js:57:25)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
   [Symbol(code)]: 'COMMAND_INTERACTION_OPTION_NOT_FOUND'
 }
```

**Comment by iakzs** [comment]
nvm i found the error my bad
