### ISSUE TITLE
'name' of undefined

### ISSUE THREAD

**Issue by SrStellar** [SudhanPlayz/Discord-MusicBot#157]
Unhandled Rejection at:  Promise {
  <rejected> TypeError: Cannot read property 'name' of undefined
      at /home/runner/Discord-MusicBot/commands/help.js:16:55
      at Map.forEach (<anonymous>)
      at Object.run (/home/runner/Discord-MusicBot/commands/help.js:14:25)
      at module.exports (/home/runner/Discord-MusicBot/events/message.js:32:9)
      at Client.emit (events.js:314:20)
      at MessageCreateAction.handle (/home/runner/Discord-MusicBot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
      at Object.module.exports [as MESSAGE_CREATE] (/home/runner/Discord-MusicBot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
      at WebSocketManager.handlePacket (/home/runner/Discord-MusicBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
      at WebSocketShard.onPacket (/home/runner/Discord-MusicBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
      at WebSocketShard.onMessage (/home/runner/Discord-MusicBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
} reason:  TypeError: Cannot read property 'name' of undefined
    at /home/runner/Discord-MusicBot/commands/help.js:16:55
    at Map.forEach (<anonymous>)
    at Object.run (/home/runner/Discord-MusicBot/commands/help.js:14:25)
    at module.exports (/home/runner/Discord-MusicBot/events/message.js:32:9)
    at Client.emit (events.js:314:20)
    at MessageCreateAction.handle (/home/runner/Discord-MusicBot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/Discord-MusicBot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/Discord-MusicBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/runner/Discord-MusicBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/Discord-MusicBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
  

plz fix it

**Comment by joeyk710** [comment]
Have you made any edits to your version of the code?

**Comment by SrStellar** [comment]
look, i translated it into portuguese because i'm brazilian, does that change anything? like, I didn't change the code to run and such, I just changed the lines to Portuguese

**Comment by joeyk710** [comment]
What lines did you change to Portuguese? Can you give an example of what you changed?

**Comment by SrStellar** [comment]
![image](https://user-images.githubusercontent.com/73672850/115928585-bffe6980-a45c-11eb-8e96-237fcfb0fd6a.png)
I changed that

**Comment by SrStellar** [comment]
I even got the help command code here again, but it kept giving the same error

**Comment by joeyk710** [comment]
The error shown says `name` in the `help.js` file under line 16 is not right. Can you send a picture of line 16 of your `help.js` file?

**Comment by SrStellar** [comment]
![image](https://user-images.githubusercontent.com/73672850/115928843-2be0d200-a45d-11eb-93f2-1d37d24bd4ad.png)
the error is saying q is here...

**Comment by joeyk710** [comment]
Try changing that line to this - 
 
```
allcmds+="`"+client.config.prefix+cmdinfo.name+" "+cmdinfo.usage+"` ~ "+cmdinfo.description+"\n"

        })
        ```

**Comment by SrStellar** [comment]
okay

**Comment by SrStellar** [comment]
![image](https://user-images.githubusercontent.com/73672850/115929383-1cae5400-a45e-11eb-8740-6e9003547fbb.png)
same error occurred

**Comment by joeyk710** [comment]
Okay. What I would do create a 2nd bot and run that one to see if the same error occurs. Then, slowly change a text field one at a time and run the bot in-between to see if the error happens when you're changing it. Let me know what happens

**Comment by SrStellar** [comment]
I'll get the whole code again and see if it will, in fact I'll upload the entire bot to see if it will

**Comment by joeyk710** [comment]
> I'll get the whole code again and see if it will, in fact I'll upload the entire bot to see if it will

Alright. If you have more issues, I can help you more in the discord support server!

**Comment by SrStellar** [comment]
okay, i'm going in

**Comment by joeyk710** [comment]
If you don't need any more help, this issue will be closed soon.
