### ISSUE TITLE
Error: input stream: Status code: 416

### ISSUE THREAD

**Issue by Alonso245** [SudhanPlayz/Discord-MusicBot#20]
The bot throws me this error after being on for a while and stops playing the music

Error: input stream: Status code: 416
    at ClientRequest.<anonymous> (\Discord-MusicBot-master\node_modules\miniget\dist\index.js:156:27)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)

**Comment by SudhanPlayz** [comment]
Can you say how to reproduce this error? So i can try fixing it

**Comment by Alonso245** [comment]
Well, when using the command "Play" <Such a song> plays normal and after a while it stops playing and it gives me that error.

**Comment by SudhanPlayz** [comment]
Maybe your connection problem since its a Range Problem. Probably while downloading the music to play. I don't see any errors since I have played music bot like 2 days nonstop
