### ISSUE TITLE
????

### ISSUE THREAD

**Issue by sam920829** [SudhanPlayz/Discord-MusicBot#221]
Z [HeadersTimeoutError]: Headers Timeout Error
    at Timeout.lt [as _onTimeout] (C:\Users\user\Downloads\Discord-MusicBot-master (4)\Discord-MusicBot-master\node_modules\petitio\dist\index.js:4:5697)
    at listOnTimeout (internal/timers.js:556:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
}

**Comment by joeyk710** [comment]
#220

**Comment by joeyk710** [comment]
#213
