### ISSUE TITLE
cant use

### ISSUE THREAD

**Issue by thanhtrung1232** [SudhanPlayz/Discord-MusicBot#248]
 node index.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'discord.js'
Require stack:
- /home/runner/Discord-MusicBot/structures/DiscordMusicBot.js
- /home/runner/Discord-MusicBot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/Discord-MusicBot/structures/DiscordMusicBot.js:1:46)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/Discord-MusicBot/structures/DiscordMusicBot.js',
    '/home/runner/Discord-MusicBot/index.js'
  ]
}
exit status 1

**Comment by joeyk710** [comment]
This is a basic node error. It tells you what module is missing. Type `npm i` in your console.
