### ISSUE TITLE
Local lava server doesnt work

### ISSUE THREAD

**Issue by VerstreuteSeele** [SudhanPlayz/Discord-MusicBot#317]
Using a local lavalink install and just using either "localhost", "127.0.0.1" or the public IP fails. with 

`(node:23520) UnhandledPromiseRejectionWarning: TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Authorization"
    at ClientRequest.setHeader (_http_outgoing.js:561:3)
    at new ClientRequest (_http_client.js:251:14)
    at request (http.js:50:10)
    at get (http.js:54:15)
    at initAsClient (C:\Users\fisch\Desktop\Discord-MusicBot-master\node_modules\ws\lib\websocket.js:675:31)
    at new WebSocket (C:\Users\fisch\Desktop\Discord-MusicBot-master\node_modules\ws\lib\websocket.js:71:7)
    at Node.connect (C:\Users\fisch\Desktop\Discord-MusicBot-master\node_modules\erela.js\dist\structures\Node.js:115:23)
    at Manager.init (C:\Users\fisch\Desktop\Discord-MusicBot-master\node_modules\erela.js\dist\structures\Manager.js:119:18)
    at module.exports (C:\Users\fisch\Desktop\Discord-MusicBot-master\events\ready.js:10:20)
    at DiscordMusicBot.emit (events.js:315:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by VerstreuteSeele** [comment]
nah i was just dumb

**Comment by ViraajRandhawa** [comment]
Im having this problem what'd u do to fix it?
