### ISSUE TITLE
TypeError: client.Build is not a function

### ISSUE THREAD

**Issue by 00000n** [SudhanPlayz/Discord-MusicBot#402]
TypeError: client.Build is not a function
    at Object.<anonymous> (/home/runner/Discord-MusicBot/index.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
exit status 1

**Comment by joeyk710** [comment]
So make sure ur botconfig is completely filled out. Nothing can be empty. If everything is filled out and it still happens then re-fork the repo and try running it again. Otherwise, this is all I can do to help.

**Comment by SudhanPlayz** [comment]
Change node version

**Comment by Blipae** [comment]
> Change node version

to what version?

**Comment by JotaroKujo0525** [comment]
Wha

**Comment by JotaroKujo0525** [comment]
This error occurs when you didn't fill up your whole config.js/botconfig.js

**Comment by Blipae** [comment]
> This error occurs when you didn't fill up your whole config.js/botconfig.js

I have the file completely full

**Comment by JotaroKujo0525** [comment]
then why would it leave an error if it is
