### ISSUE TITLE
(node:435) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown interaction

### ISSUE THREAD

**Issue by Trentyn** [SudhanPlayz/Discord-MusicBot#409]
(node:435) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown interaction
    at RequestHandler.execute (/home/runner/Quradenir/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Quradenir/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async Object.interaction.send (/home/runner/Quradenir/structures/DiscordMusicBot.js:89:16)
(node:435) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:435) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by joeyk710** [comment]
slash commands were made in djs v12 so they do not work well which you have to understand. please wait until we update the bot to djs v13 so the slash commands will work better.

next time, dont post an error without explaining the problem
