### ISSUE TITLE
client.build error

### ISSUE THREAD

**Issue by NONPLAYT** [SudhanPlayz/Discord-MusicBot#476]
**Please describe the problem you are having in as much detail as possible: im updated bot to newer version and when I want to start bot I get this error**

**Include a reproducible code sample here, if possible:**

```js
021-10-11T17:42:31.722364+00:00 app[web.1]: /app/index.js:4
2021-10-11T17:42:31.722383+00:00 app[web.1]: client.build();
2021-10-11T17:42:31.722384+00:00 app[web.1]:        ^
2021-10-11T17:42:31.722384+00:00 app[web.1]: 
2021-10-11T17:42:31.722384+00:00 app[web.1]: TypeError: client.build is not a function
2021-10-11T17:42:31.722385+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:4:8)
2021-10-11T17:42:31.722385+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2021-10-11T17:42:31.722386+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2021-10-11T17:42:31.722386+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:950:32)
2021-10-11T17:42:31.722386+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2021-10-11T17:42:31.722387+00:00 app[web.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
2021-10-11T17:42:31.722387+00:00 app[web.1]:     at internal/main/run_main_module.js:17:47
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version:14.18.0
- Operating system: using heroku stock20
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by gopla** [comment]
hello, could you describe how to solve this error?
thanks

**Comment by priyam1234-spec** [comment]
check if the botconfig.js if its filled or not 
if it is filled and it shows that start a new project

**Comment by gopla** [comment]
ah, i've figured need to install dotenv package
thanks!
