### ISSUE TITLE
Play error

### ISSUE THREAD

**Issue by NONPLAYT** [SudhanPlayz/Discord-MusicBot#565]
**Please describe the problem you are having in as much detail as possible:**
When typing >play and link to video, bot not playing music and send this error

```js
2021-11-14T19:28:19.543388+00:00 app[web.1]: RangeError: Provided argument must be present.
2021-11-14T19:28:19.543397+00:00 app[web.1]:     at Function.validate (/app/node_modules/erela.js/dist/structures/Utils.js:46:19)
2021-11-14T19:28:19.543400+00:00 app[web.1]:     at Queue.add (/app/node_modules/erela.js/dist/structures/Queue.js:38:33)
2021-11-14T19:28:19.543400+00:00 app[web.1]:     at Object.run (/app/commands/play.js:86:34)
2021-11-14T19:28:19.543400+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

But when Im using slash commands, music is playing

**Further details:**

- discord.js version: 12.5.3
- Node.js version: 14.18.1
- Operating system: Heroku stock-20
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Relevant client options:**

- partials: none
- gateway intents: all
- other: none

**Comment by DarrenOfficial** [comment]
what version of erela.js are you using?

**Comment by NONPLAYT** [comment]
2.3.2

**Comment by DarrenOfficial** [comment]
try updating it to 2.3.3

**Comment by NONPLAYT** [comment]
I'll do it as soon as I can and write here about the problem, don't close the issue yet

**Comment by DarrenOfficial** [comment]
okay

**Comment by DarrenOfficial** [comment]
if that doesn’t seem to fix it, downgrading to node 12 or upgrade to node 16

**Comment by NONPLAYT** [comment]
Now Im dont get this error (upgraded to erela.js and to node 16), but now when im enter command >play music video, bot connecting to the VC and disconnecting in next 5 seconds with "Queue is ended"

**Comment by DarrenOfficial** [comment]
lavalink issue, you can either make your own lavalink or use a public one i.e. https://mylavalink.cf

**Comment by Kakarot-0690** [comment]
Problem i guess then
