### ISSUE TITLE
Cannot read properties

### ISSUE THREAD

**Issue by Vretu-Dev** [SudhanPlayz/Discord-MusicBot#591]
What is this issue

`TypeError: Cannot read properties of undefined (reading 'send')
    at Manager. (/home/Discord-MusicBot/structures/DiscordMusicBot.js:189:54)
    at Manager.emit (node:events:390:28)
    at Node.queueEnd (/home/Discord-MusicBot/node_modules/erela.js/dist/structures/Node.js:325:22)
    at Node.trackEnd (/home/Discord-MusicBot/node_modules/erela.js/dist/structures/Node.js:320:25)
    at Node.handleEvent (/home/Discord-MusicBot/node_modules/erela.js/dist/structures/Node.js:241:18)
    at Node.message (/home/Discord-MusicBot/node_modules/erela.js/dist/structures/Node.js:222:22)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (/home/Discord-MusicBot/node_modules/ws/lib/websocket.js:983:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (/home/Discord-MusicBot/node_modules/ws/lib/receiver.js:517:14)`

CODE LINES
![image](https://user-images.githubusercontent.com/82831707/144497952-9f6abf4b-3271-4623-a7ee-61ab6216a2c2.png)

**Comment by JotaroKujo0525** [comment]
![Screenshot_20211203_064107](https://user-images.githubusercontent.com/77835007/144514709-15a655fe-5068-4051-b824-e5fa0067c393.jpg)
 What is this ;-;

**Comment by Vretu-Dev** [comment]
> ![Screenshot_20211203_064107](https://user-images.githubusercontent.com/77835007/144514709-15a655fe-5068-4051-b824-e5fa0067c393.jpg) What is this ;-;

I don't know. This is error screen with pm2 proces manager.

**Comment by JotaroKujo0525** [comment]
> > ![Screenshot_20211203_064107](https://user-images.githubusercontent.com/77835007/144514709-15a655fe-5068-4051-b824-e5fa0067c393.jpg) What is this ;-;
> 
> I don't know. This is error screen with pm2 proces manager.

Recommend you to ask in the discord server, it'll be much harder if we resolve it here

**Comment by Vretu-Dev** [comment]
> > > ![Screenshot_20211203_064107](https://user-images.githubusercontent.com/77835007/144514709-15a655fe-5068-4051-b824-e5fa0067c393.jpg) What is this ;-;
> > 
> > 
> > I don't know. This is error screen with pm2 proces manager.
> 
> Recommend you to ask in the discord server, it'll be much harder if we resolve it here

Okay

**Comment by Vretu-Dev** [comment]
Move Issue in Discord Server
