### ISSUE TITLE
how do i fix this

### ISSUE THREAD

**Issue by wolf498** [SudhanPlayz/Discord-MusicBot#636]
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:23 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: bassboost
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:23 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: bump
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:23 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: clear
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:23 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: config
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:23 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: disconnect
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:23 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: grab
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: bump
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: clear
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: config
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: disconnect
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: grab
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: help
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: invite
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: loop
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: loopqueue
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: lyrics
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: help
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: invite
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: loop
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: loopqueue
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: lyrics
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: move
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: nowplaying
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: pause
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: play
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: queue
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: move
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: nowplaying
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: pause
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: play
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: queue
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: resume
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: search
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: shuffle
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: skip
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:24 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: skipto
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:25 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: resume
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:25 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: search
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:25 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: shuffle
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:25 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: skip
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:25 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: skipto
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:25 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: stats
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:25 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: volume
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:25 | Info: [Slash Command]: [POST-FAILED] Guild 917663154111148033, Command: youtube
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/917663154111148033/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:25 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: stats
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:25 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: volume
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}
8:0:2022 - 19:25 | Info: [Slash Command]: [POST-FAILED] Guild 792068899083780126, Command: youtube
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/test-2/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/test-2/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/924739713938636810/guilds/792068899083780126/commands',
  code: 50001,
  httpStatus: 403
}

**Comment by JotaroKujo0525** [comment]
This is not a bug bruh

**Comment by JotaroKujo0525** [comment]
Bug is different from error

**Comment by JotaroKujo0525** [comment]
Common dashboard error: 

invalid OAuth2 redirect_uri 

Steps to fix:
 > 1) Make sure to fill out all the contents on botconfig.js.
 > 2) In the website part of the botconfig.js, in line 20 to be exact. Put there the website url. Note: all of those needs to be lowercase, I.e.: https://discordmusicbot.darrennathanael.com
 > 3) After that, go to your application on discord developer portal, and go to Oauth2 -> Redirects, there add the url site then /api/callback. It needs to be both https and http.
 > 4) Click Save Changes
 > 5) Restart your bot.

If you are using hosting the bot with Heroku, your Website in the botconfig.js on line 20 needs to be set to 0.0.0.0
