### ISSUE TITLE
24/7 bug

### ISSUE THREAD

**Issue by ZayanPlayz** [SudhanPlayz/Discord-MusicBot#642]
Error: secret option required for sessions
    at session (/home/runner/Discord-MusicBot/node_modules/express-session/index.js:200:12)
    at Layer.handle [as handle_request] (/home/runner/Discord-MusicBot/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:317:13)
    at /home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:335:12)
    at next (/home/runner/Discord-MusicBot/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/runner/Discord-MusicBot/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:314:20)
    at SendStream.error (/home/runner/Discord-MusicBot/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/home/runner/Discord-MusicBot/node_modules/send/index.js:421:12)

**Comment by ZayanPlayz** [comment]
I can't run my music bot 24/7 because of this error. any help?

**Comment by DarrenOfficial** [comment]
Your secret key is wrong

**Comment by DarrenOfficial** [comment]
go to discord.com/developers then click your bot then find bot secrets copy paste that, put that in the botconfig

**Comment by ZayanPlayz** [comment]
sorry for late reply but it worked, ty
