### ISSUE TITLE
v5 Bot disconnect crash

### ISSUE THREAD

**Issue by DarrenOfficial** [SudhanPlayz/Discord-MusicBot#696]
🔫 Fix voice when manually disconnected sometimes show
```js
RangeError: No voice channel has been set.
    at Object.connect (/root/discord/DiscordMusic/node_modules/erela.js/dist/structures/Player.js:146:19)
    at SlashCommand.run (/root/discord/DiscordMusic/commands/slash/play.js:26:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
RangeError: No voice channel has been set.
    at Object.connect (/root/discord/DiscordMusic/node_modules/erela.js/dist/structures/Player.js:146:19)
    at SlashCommand.run (/root/discord/DiscordMusic/commands/slash/play.js:26:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
RangeError: No voice channel has been set.
    at Object.connect (/root/discord/DiscordMusic/node_modules/erela.js/dist/structures/Player.js:146:19)
    at SlashCommand.run (/root/discord/DiscordMusic/commands/slash/play.js:26:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
and also the bot will say this
![Did i rickroll myself making this? yes](https://z.darrennathanael.com/i/ce40b30b.png)

**Comment by DarrenOfficial** [comment]
also don't question me why am I alive at 4 am

**Comment by DarrenOfficial** [comment]
Fixed. https://git.darrennathanael.com/DarrenOfficial/DiscordMusic/commit/7391cfff87b8a3d31b96c9e86d2d8bfb295840bd
