### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'on')

### ISSUE THREAD

**Issue by guilhermeziito** [SudhanPlayz/Discord-MusicBot#735]
**When i try to start the bot im my machine its not start**

```/etc/node_modules/appmetrics/lib/aspect.js:56
    var existing = target[methodName];
                         ^
TypeError: Cannot read properties of undefined (reading 'on')
    at /etc/node_modules/appmetrics/lib/aspect.js:56:26
    at Array.forEach (\u003canonymous\u003e)
    at Object.exports.before (/etc/node_modules/appmetrics/lib/aspect.js:55:9)
    at SocketioProbe.attach (/etc/node_modules/appmetrics/probes/socketio-probe.js:69:12)
    at /etc/node_modules/appmetrics/index.js:155:27
    at Module.newFunc (/etc/node_modules/appmetrics/lib/aspect.js:102:14)
    at Module.newFunc [as require] (/etc/node_modules/ibmapm-embed/appmetrics-zipkin/lib/aspect.js:101:26)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.\u003canonymous\u003e (/home/node/structures/DiscordMusicBot.js:4:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

**Further details: using node index.js ocurre this errors, my host dont use the npm install and ocurre this. how to fix?**

- discord.js version: 12.5.3
- Node.js version: 16.14.0
- Operating system: win10 
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by JotaroKujo0525** [comment]
wha-

**Comment by JotaroKujo0525** [comment]
tell me, what did you do for this error to occur
