### ISSUE TITLE
Console getting spammed with errors but still working

### ISSUE THREAD

**Issue by momochqn** [SudhanPlayz/Discord-MusicBot#741]
The console is getting spammed with Errors:

```js
27:1:2022 - 14:42 | Info: [Slash Command]: [POST-FAILED] Guild 564880520219983883, Command: youtube
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/m9mo/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/m9mo/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/m9mo/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/895283932252241940/guilds/564880520219983883/commands',
  code: 50001,
  httpStatus: 403
}
```
It gives this error for every command in every server but it still works fine.

**Further details:**

- discord.js version: 12.5.3
- Node.js version: 12.22.5
- Operating system: Debian 11 Linux
- Priority this issue should have – please be realistic and elaborate if possible: low

**Comment by DarrenOfficial** [comment]
scope issue, make sure to invite your bot with applications.commands scope.
