### ISSUE TITLE
Make Commands Guild-Only

### ISSUE THREAD

**Issue by kaaax0815** [SudhanPlayz/Discord-MusicBot#77]
When DMing the Bot (prefix)play the bots prints error.
I found this: https://discordjs.guide/commando/guild-only.html but this only works when using commando
Error (hosted on replit):
```
      at WebSocket.emit (events.js:315:20)
} reason:  TypeError: Cannot read property 'voice' of null
    at Object.run (/home/runner/discordjs/commands/play.js:17:34)
    at module.exports (/home/runner/discordjs/events/message.js:32:9)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (/home/runner/discordjs/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/discordjs/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/discordjs/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/runner/discordjs/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/discordjs/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/runner/discordjs/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
```

**Comment by SudhanPlayz** [comment]
This doesnt the full error and just return before reading command if message was sent on dms

**Comment by kaaax0815** [comment]
This is the Full Log:
```Unhandled Rejection at:  Promise {
  <rejected> TypeError: Cannot read property 'voice' of null
      at Object.run (/home/runner/discordjs/commands/play.js:17:34)
      at module.exports (/home/runner/discordjs/events/message.js:32:9)
      at Client.emit (events.js:315:20)
      at MessageCreateAction.handle (/home/runner/discordjs/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
      at Object.module.exports [as MESSAGE_CREATE] (/home/runner/discordjs/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
      at WebSocketManager.handlePacket (/home/runner/discordjs/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
      at WebSocketShard.onPacket (/home/runner/discordjs/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
      at WebSocketShard.onMessage (/home/runner/discordjs/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
      at WebSocket.onMessage (/home/runner/discordjs/node_modules/ws/lib/event-target.js:132:16)
      at WebSocket.emit (events.js:315:20)
} reason:  TypeError: Cannot read property 'voice' of null
    at Object.run (/home/runner/discordjs/commands/play.js:17:34)
    at module.exports (/home/runner/discordjs/events/message.js:32:9)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (/home/runner/discordjs/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/discordjs/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/discordjs/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/runner/discordjs/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/discordjs/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/runner/discordjs/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)`
```
Yeah as i said that you dont use Commando

**Comment by SudhanPlayz** [comment]
Just return on `events/message.js` if message channel type is dm

**Comment by kaaax0815** [comment]
I think thats a "feature" you should put on your todo list. i think the console line would be happy xd (sorry for the bad joke)

**Comment by SudhanPlayz** [comment]
Lmao, yea sure will do
