### ISSUE TITLE
Play command not working for replit

### ISSUE THREAD

**Issue by Discobotdevlolhehe** [SudhanPlayz/Discord-MusicBot#778]
**The play command dosent work. When ever I run the command, I always end up with the error saying "no matches found - given song"**

// In the terminal it says:
angeError: Provided argument must be present.
    at Function.validate (/home/runner/Lava-Music/node_modules/erela.js/dist/structures/Utils.js:46:19)
    at Queue.add (/home/runner/Lava-Music/node_modules/erela.js/dist/structures/Queue.js:38:33)
    at Object.run (/home/runner/Lava-Music/commands/play.js:169:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Further details:**

- discord.js version:
- 12.5.3
- Node.js version:
- 12.22.10
- Operating system:
- Linux 
- The play command doesn't work on replit. I also tried on my win 11 pc and end up with the same result as given in the title. I followed all the steps correctly and it was working good for around 2 months but now it stopped

**Relevant client options:**

- partials: none
- gateway intents: none
- other: 
- - permissions: 2205281600

<!--

screen shots:
![image](https://user-images.githubusercontent.com/94049800/161393022-bccb21fe-912e-48ae-bc67-02c3637a5d3d.png)


-->

**Comment by JotaroKujo0525** [comment]
Erela.js problem, restart and it should be fine

**Comment by LetThatSinkIn** [comment]
> Erela.js problem, restart and it should be fine

I'm having the same issue, started yesterday - restarting the replit doesn't fix it...

**Comment by JotaroKujo0525** [comment]
Start a new project and run, we can't do anything about this because as I said, it's a package problem

**Comment by Xxcoolromegamer** [comment]
> Bro this bot is for v13, are you using the version with the buttons on the player? If yes then upgrade to NodeJS 16 and use discord.js v13 for it to be fixed.

actually he is talking about v12

**Comment by Discobotdevlolhehe** [comment]
Thank you everyone who helped me in this. Its working now, just had to fork it again
