### ISSUE TITLE
Error when use play command.

### ISSUE THREAD

**Issue by hannieboba** [SudhanPlayz/Discord-MusicBot#797]
Hi, im using latest source bot code on replit. but when im use the play command the bot doesn't want to play the song.
-
RangeError: Provided argument must be present.
    at Function.validate (/home/runner/Discord-MusicBot-1/node_modules/erela.js/dist/structures/Utils.js:46:19)
    at Queue.add (/home/runner/Discord-MusicBot-1/node_modules/erela.js/dist/structures/Queue.js:38:33)
    at Object.run (/home/runner/Discord-MusicBot-1/commands/play.js:169:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
![image_2022-04-17_174009270](https://user-images.githubusercontent.com/78210677/163710966-837ac24e-59fa-40d7-9058-81ffe7c9f1be.png)
![image_2022-04-17_174036798](https://user-images.githubusercontent.com/78210677/163710974-f75487b9-197a-4456-963e-264188bc678d.png)

**Comment by XstreamSpeed** [comment]
Made by Hannie 👀

**Comment by kotru21** [comment]
Try to use link instead of name
