### ISSUE TITLE
Error parsing info: Unable to retrieve video metadata

### ISSUE THREAD

**Issue by NikiRakshu** [SudhanPlayz/Discord-MusicBot#83]
Allways i am getting This error

`Error: input stream: Error parsing info: Unable to retrieve video metadata
    at getWatchPage (D:\Discord-MusicBot-3.0.0\node_modules\ytdl-core\lib\info.js:75:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async exports.getBasicInfo (D:\Discord-MusicBot-3.0.0\node_modules\ytdl-core\lib\info.js:84:22)
    at async Map.getOrSet (D:\Discord-MusicBot-3.0.0\node_modules\ytdl-core\lib\cache.js:24:19)
    at async exports.getInfo (D:\Discord-MusicBot-3.0.0\node_modules\ytdl-core\lib\info.js:226:14)
    at async Map.getOrSet (D:\Discord-MusicBot-3.0.0\node_modules\ytdl-core\lib\cache.js:24:19)`

**Comment by SourCreamCulture** [comment]
Update your ytdl core dependency to the latest version @NikiRakshu

**Comment by Colonel-Ltd** [comment]
Fix?

**Comment by SudhanPlayz** [comment]
If no reply within 24 hours close this issue

**Comment by Colonel-Ltd** [comment]
> Update your ytdl core dependency to the latest version @NikiRakshu

Fixed
