### ISSUE TITLE
Error with v5 and replit

### ISSUE THREAD

**Issue by Toodo** [SudhanPlayz/Discord-MusicBot#881]
**Please describe the problem you are having in as much detail as possible: I was gonna update my bot downloaded latest v5(14573ad 3 hours ago) and try to boot it on repelit.com got some erroes**

**Include a reproducible code sample here, if possible:**

```js
 panic: Scope location 1821 must be greater than 1825 [recovered]
    panic: Scope location 1821 must be greater than 1825

goroutine 149 [running]:
github.com/amasad/esparse/parser.Parse.func1()
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:7827 +0x54
panic({0x7dabc0, 0xc000224a10})
    runtime/panic.go:1038 +0x215
github.com/amasad/esparse/parser.(*parser).pushScopeForParsePass(0xc00075d080, 0x2, {0x8945f0})
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:272 +0x2b9
github.com/amasad/esparse/parser.(*parser).parseParenExpr(0xc00075d080, {0x640e70}, {0xc0, 0x0})
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:1759 +0xcfd
github.com/amasad/esparse/parser.(*parser).parsePrefix(0xc00075d080, 0x1, 0x0)
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:1915 +0x5ab
github.com/amasad/esparse/parser.(*parser).parseExpr(0xc00075d0c0, 0xc00075d080)
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:2435 +0x25
github.com/amasad/esparse/parser.(*parser).parseAndDeclareDecls(0xc00075d080, 0xe0, {0x1, 0x0, 0x0, 0x0, 0x0, 0x0})
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:3182 +0x19f
github.com/amasad/esparse/parser.(*parser).parseStmt(0xc00075d080, {0x1, 0x0, 0x0, 0x0, 0x0, 0x0})
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:4014 +0x58be
github.com/amasad/esparse/parser.(*parser).parseStmtsUpTo(0xc00075d080, 0x12, {0x1, 0x0, 0x0, 0x0, 0x0, 0x0})
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:4834 +0xf7
github.com/amasad/esparse/parser.(*parser).parseFnBodyStmts(0xc00075d080, {0x90, 0x9a, 0x6f, 0x0})
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:4817 +0x9d
github.com/amasad/esparse/parser.(*parser).parseFn(0xc00075d080, 0x0, {0xb8, 0x59, 0x23, 0x0})
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:3529 +0x7c5
github.com/amasad/esparse/parser.(*parser).parseFnExpr(0xc00075d080, {0x2358f8}, 0xc0)
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:1651 +0x1a5
github.com/amasad/esparse/parser.(*parser).parsePrefix(0xc00075d080, 0x1, 0xc000307d40)
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:2097 +0x1e56
github.com/amasad/esparse/parser.(*parser).parseExprOrBindings(0xc00075d0c0, 0xc000049200, 0xc0007fe877)
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:2431 +0x28
github.com/amasad/esparse/parser.(*parser).parseProperty(0xc00075d080, 0x0, 0x0, {0x0, 0x0, 0x0}, 0xc0008964b8)
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:1430 +0x1b38
github.com/amasad/esparse/parser.(*parser).parsePrefix(0xc00075d080, 0x1, 0xc000896aa8)
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:2227 +0x33dd
github.com/amasad/esparse/parser.(*parser).parseExprOrBindings(0xc00075d0c0, 0x1d85d68, 0x7f4ac0)
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:2431 +0x28
github.com/amasad/esparse/parser.(*parser).parsePrefix(0xc00075d080, 0x1, 0x0)
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:2176 +0x2d85
github.com/amasad/esparse/parser.(*parser).parseExpr(0x40eb27, 0x203000)
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:2435 +0x25
github.com/amasad/esparse/parser.(*parser).parseCallArgs(0xc00075d080)
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:2933 +0x108
github.com/amasad/esparse/parser.(*parser).parseSuffix(0xc00075d080, {{0x0}, {0x1009a80, 0xc00089c400}}, 0x0, 0x0)
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:2545 +0x190f
github.com/amasad/esparse/parser.(*parser).parseExpr(0xc00075c840, 0x0)
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:2435 +0x3f
github.com/amasad/esparse/parser.(*parser).parseStmt(0xc00075d080, {0x1, 0x1, 0x0, 0x0, 0x0, 0x0})
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:4592 +0x637e
github.com/amasad/esparse/parser.(*parser).parseStmtsUpTo(0xc00075d080, 0x0, {0x1, 0x1, 0x0, 0x0, 0x0, 0x0})
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:4834 +0xf7
github.com/amasad/esparse/parser.Parse({0xc000000000}, {0x7, {0xc000031da0, 0x58}, {0xc000031da0, 0x58}, {_, _}}, {0x1, 0x0, ...})
    github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:7851 +0x2d3
github.com/replit/upm/internal/backends/nodejs.parseFile({0x7, {0xc000031da0, 0x58}, {0xc000031da0, 0x58}, {0xc0001f0800, 0x44a8}}, 0x810820)
    github.com/replit/upm/internal/backends/nodejs/grab.go:86 +0x1e5
created by github.com/replit/upm/internal/backends/nodejs.guessBareImports.func1
    github.com/replit/upm/internal/backends/nodejs/grab.go:136 +0x4e8


Replit: Package operation failed.
```

**Further details:**

- discord.js version: replit
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible: still have an older verison thats working

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by BioCla** [comment]
Are you able to identify the code snippet which is causing this issue?
Have you changed any piece of the code (other than the config) before encountering this error?

**Comment by Toodo** [comment]
Are you able to identify the code snippet which is causing this issue? i dont know what you are talking about sry. i downloaded latest v5 version to my computer, on replit created a new node.js upload all the files + "old config with my bot settings" 
Have you changed any piece of the code (other than the config) before encountering this error? No
What were you doing when this error occurred? trying to start the bot.
What type of replit container are you running? A normal node.js?
What Node.js version is installed? idk that one you are adding with the bot?? ^^

**Comment by JotaroKujo0525** [comment]
Hello, please reopen another repl or fork your current one, I'm pretty sure this is a replit issue or bug. The updates in that commit is just changing the package version and that shouldn't cause these errors.

**Comment by JotaroKujo0525** [comment]
Also are these really the errors showing up, I don't remember any `go` in our code

**Comment by LewdHuTao** [comment]
![image](https://user-images.githubusercontent.com/90232327/173168591-829ec1a0-d28d-4a4e-b133-fcfa7a655197.png)

i tried to run v5 latest commit in replit and get the same exact error like @Toodo 
this happened when you try to run the bot using the "Run" button. Quick fixed to this you can type `npm run start` or `node .` in shell/console but it probably will return `Cannot find module 'node:events'` as node.js 16+ is not installed. So first you can installed node.js 16 by run `bash ./kickstartReplit.sh` or run this script `npm init -y && npm i --save-dev node@16 && npm config set prefix=$(pwd)/node_modules/node && export PATH=$(pwd)/node_modules/node/bin:$PATH` in shell/console (i personally recommend you to run it in shell), after that you can run `npm run start` or `node .` to start your bot

**Comment by LewdHuTao** [comment]
I don't think this is an issues with the recent commit as it only happen when you try to run the bot using the "Run" button and not with `npm run start`, `node .` or `yarn start`.

**Comment by JotaroKujo0525** [comment]
As I thought, it's replit's fault

**Comment by JotaroKujo0525** [comment]
Okay, tldr.
Steps to reproduce this error:
Click the `Run` Button to run v5 branch in **replit**.

Steps to fix: 
Run `bash kickstartReplit.sh` and `npm run start` or `node .` on shell.

**Comment by JotaroKujo0525** [comment]
Don't hesitate to reopen the issue if you have any questions or just ask on the discord server
