### ISSUE TITLE
Unable to deploy on heroku after recent discord update

### ISSUE THREAD

**Issue by shanuflash** [SudhanPlayz/Discord-MusicBot#898]
### Unable to deploy on heroku after recent discord update.

```
/app/node_modules/discord.js/src/client/Client.js:548
       throw new TypeError('CLIENT_MISSING_INTENTS');
       ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
     at DiscordMusicBot._validateOptions (/app/node_modules/discord.js/src/client/Client.js:548:13)
     at new Client (/app/node_modules/discord.js/src/client/Client.js:76:10)
     at new DiscordMusicBot (/app/structures/DiscordMusicBot.js:22:5)
     at Object.<anonymous> (/app/index.js:3:16)
     at Module._compile (node:internal/modules/cjs/loader:1105:14)
     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
     at Module.load (node:internal/modules/cjs/loader:981:32)
     at Module._load (node:internal/modules/cjs/loader:827:12)
     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
     at node:internal/main/run_main_module:17:47 {
   [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
 }
```

- discord.js version: 13.8.0
- Node.js version: 18.3.0
- Operating system: (Heroku)

**Comment by JotaroKujo0525** [comment]
Enable intents in [developer portal] (https://discord.com/developers/applications) thx

**Comment by JotaroKujo0525** [comment]
My goodness

**Comment by JotaroKujo0525** [comment]
Epic hyperlink fail lol
