### ISSUE TITLE
Error at api/routes/data.js

### ISSUE THREAD

**Issue by XstreamSpeed** [SudhanPlayz/Discord-MusicBot#942]
**Please describe the problem you are having in as much detail as possible:**
Today I woke up to this error:
```js
TypeError: Cannot read property 'username' of null
    at /home/runner/Quadro/api/routes/data.js:9:23
    at Layer.handle [as handle_request] (/home/runner/Quadro/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/Quadro/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/runner/Quadro/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/runner/Quadro/node_modules/express/lib/router/layer.js:95:5)
    at /home/runner/Quadro/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/runner/Quadro/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/Quadro/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/runner/Quadro/node_modules/express/lib/router/index.js:175:3)
    at router (/home/runner/Quadro/node_modules/express/lib/router/index.js:47:12)TypeError: Cannot read property 'username' of null
    at /home/runner/Quadro/api/routes/data.js:9:23
    at Layer.handle [as handle_request] (/home/runner/Quadro/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/Quadro/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/runner/Quadro/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/runner/Quadro/node_modules/express/lib/router/layer.js:95:5)
    at /home/runner/Quadro/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/runner/Quadro/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/Quadro/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/runner/Quadro/node_modules/express/lib/router/index.js:175:3)
    at router (/home/runner/Quadro/node_modules/express/lib/router/index.js:47:12)
```
I was not having this error earlier or ever before, it just popped up now which is preventing my bot from logging in, although the events and commands do load.

**Include a reproducible code sample here, if possible:**
Here is my copy of DiscordMusicBot's api/routes/data.js file
```js
const { Router } = require("express");
const api = Router();

const package = require("../../package.json");
const client = require("../../")

api.get("/", (req, res) => {
  let data = {
    name: client.user.username,
    version: package.version,
    commands: client.slashCommands.map(cmd => {
      return {
        name: cmd.name,
        description: cmd.description
      }
    }),
    inviteURL: `https://discord.com/oauth2/authorize?client_id=${client.config.clientId
      }&permissions=${client.config.permissions
      }&scope=${client.config.scopes.toString().replace(/,/g, "%20")}`
  }
  res.json(data)
});

module.exports = api;
// Place your code here
```

**Further details:**

- discord.js version: v13.8.0
- Node.js version: v16.7.0
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible: High

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by XstreamSpeed** [comment]
Nevermind, fixed it by replacing ```js 
client.user.username``` to ```js
client.config.username``` where I defined username as my bot's name in a string
