### ISSUE TITLE
plz help

### ISSUE THREAD

**Issue by AayanAsim746** [SudhanPlayz/Discord-MusicBot#96]
at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    errno: -2,
    syscall: 'open',
    code: 'ENOENT',
    path: './afk.json'
  }
} reason:  Error: ENOENT: no such file or directory, open './afk.json'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at play (/home/runner/DenseSubduedTest/commands/play.js:100:29)
    at Object.run (/home/runner/DenseSubduedTest/commands/play.js:154:7)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Colonel-Ltd** [comment]
add 
`{}`
in afj.json file
