### ISSUE TITLE
[Bug] Error launching app (v5): SyntaxError: Unexpected token '}' [/lib/DiscordMusicBot.js:246]

### ISSUE THREAD

**Issue by vp-en** [SudhanPlayz/Discord-MusicBot#969]
**Please describe the problem you are having in as much detail as possible:**
Doing a `git pull` or a `git clone -b v5 https://github.com/SudhanPlayz/Discord-MusicBot.git` from the [newest commit](https://github.com/SudhanPlayz/Discord-MusicBot/commit/5396bedfd4466fe16cc68d7749b449c8951bc8e4) as of this writing, will result in the following error, trying to launch it with `node index.js`:
```
2022-07-04T11:05:57.540994799Z SyntaxError: Unexpected token '}'2022-07-04T11:05:57.541015919Z     at Object.compileFunction (node:vm:353:18)2022-07-04T11:05:57.541019436Z     at wrapSafe (node:internal/modules/cjs/loader:1040:15)2022-07-04T11:05:57.541021670Z     at Module._compile (node:internal/modules/cjs/loader:1076:27)2022-07-04T11:05:57.541024756Z     at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)2022-07-04T11:05:57.541027110Z     at Module.load (node:internal/modules/cjs/loader:988:32)2022-07-04T11:05:57.541029274Z     at Module._load (node:internal/modules/cjs/loader:834:12)2022-07-04T11:05:57.541031378Z     at Module.require (node:internal/modules/cjs/loader:1012:19)2022-07-04T11:05:57.541033653Z     at require (node:internal/modules/cjs/helpers:102:18)2022-07-04T11:05:57.541035766Z     at Object.<anonymous> (/usr/src/app/index.js:4:25)2022-07-04T11:05:57.541038031Z     at Module._compile (node:internal/modules/cjs/loader:1112:14)2022-07-04T11:05:57.541040245Z2022-07-04T11:05:57.541042279Z Node.js v18.4.02022-07-04T11:05:59.533336820Z /usr/src/app/lib/DiscordMusicBot.js:2462022-07-04T11:05:59.533353892Z                  })2022-07-04T11:05:59.533357690Z                  ^2022-07-04T11:05:59.533360455Z2022-07-04T11:05:59.533362589Z SyntaxError: Unexpected token '}'2022-07-04T11:05:59.533364673Z     at Object.compileFunction (node:vm:353:18)2022-07-04T11:05:59.533366677Z     at wrapSafe (node:internal/modules/cjs/loader:1040:15)2022-07-04T11:05:59.533368720Z     at Module._compile (node:internal/modules/cjs/loader:1076:27)2022-07-04T11:05:59.533371255Z     at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)2022-07-04T11:05:59.533373449Z     at Module.load (node:internal/modules/cjs/loader:988:32)2022-07-04T11:05:59.533375473Z     at Module._load (node:internal/modules/cjs/loader:834:12)2022-07-04T11:05:59.533377577Z     at Module.require (node:internal/modules/cjs/loader:1012:19)2022-07-04T11:05:59.533379641Z     at require (node:internal/modules/cjs/helpers:102:18)2022-07-04T11:05:59.533381655Z     at Object.<anonymous> (/usr/src/app/index.js:4:25)2022-07-04T11:05:59.533384510Z     at Module._compile (node:internal/modules/cjs/loader:1112:14)2022-07-04T11:05:59.533386855Z2022-07-04T11:05:59.533388888Z Node.js v18.4.02022-07-04T11:06:03.211017021Z /usr/src/app/lib/DiscordMusicBot.js:2462022-07-04T11:06:03.211032741Z                  })2022-07-04T11:06:03.211039123Z                  ^2022-07-04T11:06:03.211043551Z2022-07-04T11:06:03.211047649Z SyntaxError: Unexpected token '}'2022-07-04T11:06:03.211051927Z     at Object.compileFunction (node:vm:353:18)2022-07-04T11:06:03.211056175Z     at wrapSafe (node:internal/modules/cjs/loader:1040:15)2022-07-04T11:06:03.211066655Z     at Module._compile (node:internal/modules/cjs/loader:1076:27)2022-07-04T11:06:03.211070812Z     at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)2022-07-04T11:06:03.211073117Z     at Module.load (node:internal/modules/cjs/loader:988:32)2022-07-04T11:06:03.211075291Z     at Module._load (node:internal/modules/cjs/loader:834:12)2022-07-04T11:06:03.211077345Z     at Module.require (node:internal/modules/cjs/loader:1012:19)2022-07-04T11:06:03.211079419Z     at require (node:internal/modules/cjs/helpers:102:18)2022-07-04T11:06:03.211081573Z     at Object.<anonymous> (/usr/src/app/index.js:4:25)2022-07-04T11:06:03.211083897Z     at Module._compile (node:internal/modules/cjs/loader:1112:14)
```

Log can also be found [here](https://paste.ec/paste/JRdNZnlZ#lNIjTgoQw2SEhv5pT2CESHguCIcPVCOi30MgzifFsNi).

It seems to be referring to this line:
https://github.com/SudhanPlayz/Discord-MusicBot/blob/5396bedfd4466fe16cc68d7749b449c8951bc8e4/lib/DiscordMusicBot.js#L246

### Essentials:

- Bot Version: v5
- Commit Hash: 5396bedfd4466fe16cc68d7749b449c8951bc8e4
- Node.js version: node:18-alpine (using Docker)
- Operating system: Docker / Ubuntu 22 LTS

#### Additional system info
- Is it virtualized? (Docker or ...) : Docker!
- What CPU is it running on (X86 or ARM or...): AMD 5950X
- Additional details that might help us figure out the problem: 
My `config.js` file [here](https://paste.ec/paste/j-V1nPWO#ipci1CSbWvM67SvxVtDhI2yEVNQ7ts4FwCbKsMiNtAr): 

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by JotaroKujo0525** [comment]
Latest commit is #945, very nice. I'll check the files changed

**Comment by JotaroKujo0525** [comment]
The issue is in #952

**Comment by JotaroKujo0525** [comment]
I'll try to fix this and find the issue

**Comment by JotaroKujo0525** [comment]
Also while this persists,recommend you to revert at 72d98ba. Thanks

**Comment by DLmass** [comment]
I have the same problem. Tried to revert to eslint - 8.18.0 but the problem is still there.

**Comment by ItzCuteAkemi** [comment]
ah crap accidentally click something in gitpod

**Comment by DevAmiyo** [comment]
> The issue is in #952

I'll try to do a fresh install of v5 and try to reproduce the issue. and then probably try to fix it..

**Comment by JotaroKujo0525** [comment]
Aight thanks

**Comment by vp-en** [comment]
Fixed, thank you 👍
